### ISSUE TITLE
no example theme anymore

### ISSUE THREAD

**Issue by tkimnguyen** [plone/plone.app.theming#120]
Plone 5 seems to be shipping now without the cited example theme (in https://github.com/plone/plone.app.theming/blob/master/docs/index.rst#what-is-a-diazo-theme) , so we should either remove it from the docs or re-add the example theme to Plone 5

**Comment by tobiasherp** [comment]
I agree. Furthermore, since the example states to use Twitter Bootstrap, it should specify the main version; there are huge differences between Bootstrap 2 (which I wouldn't use for new projects anymore) and Bootstrap 3 (Bootstrap 4 currently in beta).

**Comment by tkimnguyen** [comment]
@tobiasherp that is a good reason not to mention the version at all... not going to try to keep up with Bootstrap version changes in our docs :)

**Comment by tobiasherp** [comment]
I disagree. Currently Bootstrap 2.3.2 and 3.3.7 are offered for download, and v4 is still in alpha (alpha 6 offered for download) or beta (v4.0.0-beta.2 mentioned on http://getbootstrap.com/) status.
There is a huge difference between versions 2 and 3 which does not only involve the classes used but also the nesting logics of columns. Thus, whoever uses Bootstrap will certainly want to know about the top-level version. It can be a **lot** of work to upgrade a BS2 site to BS3.

**Comment by tkimnguyen** [comment]
If you're asking that someone re-add the example theme, then please help get that done :) Failing someone stepping up to do that work, it is better to remove the mention now.

**Comment by tobiasherp** [comment]
Since I don't have this example theme (as it used to be), I don't know whether it used Bootstrap 2 or Bootstrap 3. The first step would be to re-add it, and then update the documentation, title etc. to include this information.

**Comment by tkimnguyen** [comment]
@tobiasherp in the meantime (until someone else has the time to do that) we need the docs to be as internally consistent as possible. If you have the time to track down the information needed, please open another issue for it.
