### ISSUE TITLE
Disabling Diazo creates invalid HTML (self-closing script tags)

### ISSUE THREAD

**Issue by scy** [plone/plone.app.theming#159]
Not quite sure whether this is the right component, feel free to direct me to somewhere else.

In 5.2rc3, when I disable Diazo (to see the "vanilla" HTML), the `<script>` tags in the `<head>` are rendered as self-closing, i.e. `<script src="…" />` instead of `<script src="…"></script>`. Since self-closing `<script>` tags are invalid, the browser ignores the closing `/` and thus starts interpreting everything following the first `<script>` tag as its contents. All of the `<body>` gets eaten by it and a white page is displayed.

To reproduce, use a `buildout.cfg` like this to install a simple Plone site:

```ini
[buildout]
extends =
    https://dist.plone.org/release/5.2rc3-pending/versions.cfg
parts =
    instance

[instance]
recipe = plone.recipe.zope2instance
user = admin:admin
http-address = 9080
eggs =
    Plone
```

Run `bin/instance fg`, then log in using `admin:admin` at `localhost:9080`. Create the default site. Then log out again, and make sure you're also logged out of HTTP Basic auth.

Now, you can either try accessing http://localhost:9080/Plone/?diazo.off=1 or, using the "hosts without theming" feature, open http://127.0.0.1:9080/Plone/. In both cases, you will end up with something like this:

![screenshot of invalid HTML](https://user-images.githubusercontent.com/28629/57403172-533f2580-71d9-11e9-9f15-24b1ed169ed6.png)

Firefox 66, Chrome 74 and Edge 44 (I'm thorough…) all interpret the `<script … />` tag as never being closed and don't display any content.

Funny enough, once you're logged in and the edit bar is displayed, you can access http://localhost:9080/Plone/?diazo.off=1 and it will output correct `<script …></script>` tags instead.

I've also tried using 5.2rc2 and 5.2rc1 (simply replace `5.2rc3-pending` in the `buildout.cfg` with `5.2rc2` or `5.2rc` and rebuild), both show the same result.

**Edit:** Forgot to mention, I'm running Python 3.7. My complete Version Overview:

* Plone 5.2rc3 (5204)
* CMF 2.4.0b8
* Zope 4.0b10
* Python 3.7.3rc1 (default, Mar 13 2019, 11:01:15) [GCC 8.3.0]
* PIL 6.0.0 (Pillow)
* WSGI: On
* Server: waitress 1.2.1

**Comment by tmassman** [comment]
Commit introduced this issue:
https://github.com/plone/Products.CMFPlone/commit/181f52e4a531ab6778d1f144271ba0188aeeaa3e

**Comment by sarn0ld** [comment]
Same issue: #2870

**Comment by flipmcf** [comment]
I vote to close this issue - track the bug here: plone/Products.CMFPlone#2870

**Comment by scy** [comment]
Fine by me 👍
