### ISSUE TITLE
Wrong decode transformation with diazo on python 3

### ISSUE THREAD

**Issue by csanahuja** [plone/plone.app.theming#162]
Having a diazo theme with a `replace` pulling code from a browser view in `rules.xml` causes wrong decoded html delivery.

I.e: á shows like: Ã

Environment:
Python 3.6
Plone 5.2

Steps to reproduce
1) Define a browser view named @@test-view with the following html
```
<div id="test">á</div>
```
2) Use a `replace` rule to replace some content of the theme
```
<replace css:theme="#test" css:content="#test" href="@@test-view"/>
```

The html rendered from @@test-view its not decoded properly.

Futher investigation:
1) Code from browser views its retrived with plone.subrequest
https://github.com/plone/plone.app.theming/blob/master/src/plone/app/theming/utils.py#L136
2) Seems when executing the resolve_string method the internals of lxml put a wrong encoding
https://github.com/plone/plone.app.theming/blob/master/src/plone/app/theming/utils.py#L167
I can't figure out a solution so a quick hotfix I found was to add `meta` tag to text/html results
```
         # Line: 165
        elif content_type == 'text/html':
            result = ''.join([
                '<meta charset="utf-8"/>',
                result
                ])
```

**Comment by lodnert** [comment]
Can this be merged or do we need to investigate why this is happening

**Comment by mauritsvanrees** [comment]
I made a different PR: https://github.com/plone/plone.app.theming/pull/180
