### ISSUE TITLE
Can't use Live Preview of theme

### ISSUE THREAD

**Issue by wkbkhard** [plone/plone.app.theming#173]
May be related to blog post: https://community.plone.org/t/plone-5-2-1-theming-attributeerror-requestcontainer-object-has-no-attribute-parents/11993

- Plone 5.2.0 (5207)
- CMF 2.4.0
- Zope 4.1.1
- Python 3.6.9 (default, Nov 7 2019, 10:44:02) [GCC 8.3.0]
- PIL 6.1.0 (Pillow)
- WSGI: An
- Server: waitress 1.3.

I tried to use the Live Preview (clicking on the picture of a theme) in the @@theming-controlpanel and the following Error occurred:

```AttributeError
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 337, in publish_module
  Module ZPublisher.WSGIPublisher, line 255, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 61, in call_object
  Module plone.app.theming.browser.mapper, line 269, in getFrame
  Module plone.app.theming.utils, line 192, in findContext
AttributeError: 'RequestContainer' object has no attribute 'PARENTS'```

**Comment by djapothecary** [comment]
I created the initial post on the Plone community and have been able to resolve the issue (at least locally and temporarily) with the collowing changes:

plone.app.theming.util.py
my new instance had no published content so the request.PARENTS[0] was null. I changed the def findContext(request) method to this:

```
def findContext(request):
    """Find the context from the request
    """
    published = request.get('PUBLISHED', None)
    context = getattr(published, '__parent__', None)
    if context is not None:
        return context

    #added this additional if check
    if not request:
        for parent in request.PARENTS:
            if IContentish.providedBy(parent) or ISiteRoot.providedBy(parent):
                return parent
        #and return with in the if block
        return request.PARENTS[0]

    #change the return type if the if fails
    return request

```

and then in plone.app.theming.browser.mapper.py in the def getFrame(self) method I changed the return type as bytes were being passed but strings were expected

`
result = ''.join(str(serializer))
`

**Comment by petri** [comment]
Here, we're expecting a request:

https://github.com/plone/plone.app.theming/blob/d7c85b9b22b32458a301dde6508b65fe02ea9edf/src/plone/app/theming/utils.py#L188

But we're calling it with something else (acquisition-wrapped object that maps to the previewed site path we're trying to show):

https://github.com/plone/plone.app.theming/blob/d7c85b9b22b32458a301dde6508b65fe02ea9edf/src/plone/app/theming/browser/mapper.py#L263-L266

What should the context be? It's later used to:

https://github.com/plone/plone.app.theming/blob/d7c85b9b22b32458a301dde6508b65fe02ea9edf/src/plone/app/theming/browser/mapper.py#L277-L278

Which in turn is used to create a TALES engine expression context:

https://github.com/plone/plone.app.theming/blob/d7c85b9b22b32458a301dde6508b65fe02ea9edf/src/plone/app/theming/utils.py#L695

So my guess is that context should simply be the parent of the object that `path` maps to. Unless it's already the site root, for example.
