### ISSUE TITLE
Theming Control Panel Redesign

### ISSUE THREAD

**Issue by rohnsha0** [plone/plone.app.theming#211]
Can't we work on some visual redesign for `theming` in the control panel?
In my opinion, it should be redesigned to match current standards. As of now, it looks much more absolute and old-fashioned... :(

**Comment by stevepiercy** [comment]
First, will there continue to be a Theming control panel in future versions of Plone? In Plone 6, the new default frontend Volto has no Theming control panel because theming is handled through a completely different method. Anyway, that may influence the priority of this issue.

Second, assuming this enhancement is desired, @rohnsha0 should provide a design concept. I have no idea what "redesigned to match current standards" looks like.

**Comment by rohnsha0** [comment]
The issue I raised is upon the demo site I viewed from [Plone Demo Site](https://www.plone-demo.info/front-page)
Sorry I didn't know about the altogether new method of theme handling...
Where I can know about the same

**Comment by rohnsha0** [comment]
I can definitely give some design concepts... But before that I need to know how will the theming be managed in Plone 6...

**Comment by stevepiercy** [comment]
I do not know who owns the domain `plone-demo.info`.

There are two frontends in Plone 6. Here are the official Plone demo URLs hosted under `plone.org`:

- Classic UI: https://6-classic.demo.plone.org/
- Volto: https://6.demo.plone.org/

As you can see, Plone 6 Classic UI has a Theming control panel.

If using Volto in Plone 6, the theming method is described in the docs at https://6.dev-docs.plone.org/volto/theming/index.html.

**Comment by rohnsha0** [comment]
I don't think my issue makes sense now... 
I thought It'll be same as in v5.2.9...

**Comment by stevepiercy** [comment]
What part of what I said does not make sense? I think your issue makes sense, but you do not understand that there are two frontends for Plone 6, to help Classic UI users to transition to the new Volto frontend.

**Comment by rohnsha0** [comment]
I said my words don't make sense, not yours 🤦‍♂️
As I didn't understood the full agenda of theming at Plone 😅
I'll report regarding this in sometime...

**Comment by stevepiercy** [comment]
Maybe search on plone.org for "Roadmap"?

https://plone.org/roadmap/roadmap

**Comment by rohnsha0** [comment]
Hahaha... I'll do my research...
Until I come back to you @stevepiercy

**Comment by nileshgulia1** [comment]
@stevepiercy @rohnsha0 We really wanted to have TTW theming in Volto as we do in plone-classic. It's also something we imagined in this year's GSoC proposal along with @tkimnguyen, it needs to be a candidate somewhere in the near future.

**Comment by tkimnguyen** [comment]
That domain is owned by Andreas Jung. It's not an official site. 

It's usually best to discuss strategy in the forum https://community.plone.org where more people will see the discussion.
