### ISSUE TITLE
[Request] Release 1.1.4

### ISSUE THREAD

**Issue by nightmarebadger** [plone/plone.app.theming#35]
While upgrading a Plone site to 4.3.4 we came across the problem mentioned in issue #32. It was already fixed by 20edb5f9e967c7a92acfab067a7ec2ff5d76a624, but no release was made. 

Since this makes some Plone sites impossible to upgrade to 4.3.4 it would be great to get a new release with the fix included.

**Comment by vangheem** [comment]
I can make a release if someone gives me rights on pypi @davisagli @esteele @optilude @lrowe

**Comment by esteele** [comment]
You should have access now

**Comment by vangheem** [comment]
released: https://pypi.python.org/pypi/plone.app.theming/1.1.4
