### ISSUE TITLE
branches master vs. 1.2.x confusion

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.theming#43]
it seems that master and 1.2.x branch are both targetting 1.2.x development at the moment.

so 1.2.x is outdated, master is where the real 1.2.x development going on.

I'll delete the 1.2.x branch if this is true. Any objections?

**Comment by datakurre** [comment]
1.2.x is the last version compatible with Plone 4.3, and because of that 1.2.2 should have been released as 1.3.0.

Yet, because the mistake above, we probably cannot make any new releases from 1.2.x, and therefore deleting it might be the best option.

**Comment by jensens** [comment]
Huh, this is really bad. 
But Plone 4.3 buildout.coredev points to 1.1.x branch - so bugfixes should go there.
At least the 1.2.x branch is burnt and can be deleted imo.
@esteele what do you think?
