### ISSUE TITLE
Workaround/ fallback around "roman" package? Still needed?

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.theming#47]
Whats the reason for the hack around the `roman` package here?
https://github.com/plone/plone.app.theming/blob/master/src/plone/app/theming/__init__.py#L6
the description::

```
Some systems have a broken/missing ``roman`` module; monkey patch one in
```

is not very explicit.

We pin to roman 1.4.0. Theres already a roman 2.0.0 released. This may fix the former problems. But difficult to elobarate w/o more information.

**Comment by vangheem** [comment]
I imagine this is a relic and not needed anymore. https://github.com/plone/plone.app.theming/blob/master/src/plone/app/theming/_roman.py @optilude was the one that introduced it.
