### ISSUE TITLE
Depend on collective.js.bootstrap

### ISSUE THREAD

**Issue by rodfersou** [plone/plone.app.theming#50]
This package should use collective.js.bootstrap instead of have it's own version of bootstrap, this way I can switch to the bootstrap version I want

**Comment by vangheem** [comment]
You can always update the version of bootstrap easily by uploading a new file. Depending on is unnecessary IMO. 

However, that example bootstrap theme should be updated with latest bootstrap.

**Comment by rodfersou** [comment]
sure
