### ISSUE TITLE
When copying a new theme from control panel and giving the same id, the original disappears.

### ISSUE THREAD

**Issue by idgserpro** [plone/plone.app.theming#51]
I just downloaded Plone 5.0b1, and tried to copy a new theme from barceloneta. I decided to give the same id:

![selecao_062](https://cloud.githubusercontent.com/assets/8203476/7708915/b1ad8d9a-fe2f-11e4-9d59-cdada7de9236.png)

When giving the same id, now the original disappears from control panel. I need to delete the custom one to show the original again.

![selecao_063](https://cloud.githubusercontent.com/assets/8203476/7708916/b339b09e-fe2f-11e4-8ce0-ac16448202c9.png)

I don't know if this is the intended behavior or a bug, so I'm opening this issue.

**Comment by datakurre** [comment]
Technically that's a feature (how p.resource namespaces work). Removing the new copy should restore the original to be visible. It might make sense to prevent overriding an existing name, but that would be a change in behavior.

**Comment by idgserpro** [comment]
My 0.04c:

- Prevent overriding of an existing name (don't think it gives to much implications in code change per se, but as you said, we're losing a feature);
- Show a warning about overriding names implications;
- Show both themes on theme listing (the original won't have the delete button, but the copy will);
- Provide a message in the copied theme little box saying "there's an "original" lying on filesystem" (actually just```(active) (overrides filesystem)``` for example).

Are you familiar with the code to say if any of these are feasible? I know the priority for this would be *really* low, but I think a small improvement in this area would be it's interesting from a usability perspective.

**Comment by datakurre** [comment]
Prevent overriding should be the easiest option. Showing both is not trivial.

**Comment by idgserpro** [comment]
What about when uploading zips? Will you prevent overriding as well?

What exactly is the advantage, now, to be able to use the same id when customizing? Customize just a small part of a theme, and be able to use all ```++theme++``` resource in that namespace? I'm afraid of being the catalyst of hate for removing a feature everyone is using. :) In that case, I think just a warning should be shown.

**Comment by datakurre** [comment]
Good point about zip uploads. They should behave similarly (and currently it's similarly possible to override by zip upload).  So, the easiest would be to only warn that a filesystem theme as been overridden.

**Comment by idgserpro** [comment]
My 0.2c:

- Show a warn that a filesystem theme has been overriden;
- Show a message in the custom theme warning the override.

![selecao_065](https://cloud.githubusercontent.com/assets/8203476/7727243/ff51104a-fedd-11e4-8204-4b87755f6d6c.png)

**Comment by djay** [comment]
It could leave the use wondering what it is they override and if that's a
bad thing. If they do want to see what they overrode its not easy to do so.
They have to copy it to a new name a delete.
Is it actually useful to be be able to override the name?

**Comment by obct537** [comment]
Shoulda read this thread before going after this issue. I'm going to attempt to implement @idgserpro 's idea in his last comment. Seems like a better option than purely removing the ability to override themes.

**Comment by obct537** [comment]
I now have this working as previously suggested. However, the problem I'm noticing here is that, if you try to create an override of a user-created theme (not one on the filesystem) it crashes, whereas overriding a filesystem theme works fine. With a bit of effort, I could change it to allow overriding of user-created themes....but is this something worth investing the time into? This seems like it could potentially get messy if the user created several overrides with the same name. Simply preventing the user from doing this would be fairly easy.

Thoughts?

**Comment by vangheem** [comment]
I think overriding a TTW created theme does *not* make sense. I think you need to prevent that use-case from happening.

Overriding a file system theme does make sense though. Thanks for getting that fixed!

**Comment by idgserpro** [comment]
@vangheem once the code that fixes broke the build and it was removed from the package, you could reopen this issue?
