### ISSUE TITLE
Allow links relative to Plone site in the theme

### ISSUE THREAD

**Issue by laulaz** [plone/plone.app.theming#68]
Wouldn't it be cool if we could use relative links in the theme html file ?

For example, you created a link somewhere in the theme that should point to `/page`.
For now, if you have `<a href="/page">` in index.html, it will point to : 
 - `http://localhost:8080/page` on your machine --> not working
 - `http://site.com/page` on your domain --> working

You don't want to create a viewlet just for having a working link ...
I know this happens in Diazo, but we could maybe give the portal url to it so that it can construct relative urls.

Any opinions on this ?

**Comment by vangheem** [comment]
This is already possible. To create a link to /page, you just need to do link it in your theme file like `../page`.

All links are resolved relative to the theme file.

**Comment by laulaz** [comment]
Yes to the theme file. I meant to the portal.
Example (a dumb one), you create a link to `/contact-info`.

**Comment by vangheem** [comment]
I don't think you understand. If you can write links in your theme file like, '../contact-info' that get rewritten to 'http://myhost.com/contact-info' and 'http://127.0.0.1:8080/Plone/contact-info', why would you need absolute urls to be rewritten?

We're already doing link rewriting properly and we are not going to introduce force rewritting on absolute urls. People should not expect absolute urls to be rewritten.

**Comment by laulaz** [comment]
OK thanks for clarification !
