### ISSUE TITLE
active theme should be listed at the top

### ISSUE THREAD

**Issue by tkimnguyen** [plone/plone.app.theming#70]
If you have many Diazo themes, e.g. https://github.com/plone-ve/plonethemes.suite/, it's difficult to locate the one that is active (so you can deactivate it, inspect it, modify it). 

It would be lovely to have the active theme listed at the top.

**Comment by davilima6** [comment]
What page are you talking about? It doesn't seem @@theming-controlpanel because there active theme does come first, is highlighted and also has `(active)` in its title, same as Plone 4.
