### ISSUE TITLE
Floating items on Twitter Bootstrap theme in Plone-4.3

### ISSUE THREAD

**Issue by prakharjoshi** [plone/plone.app.theming#76]
When I tried to change the theme of plone site from default to sample bootstrap theme then I found that content is floating over that page and are not in their expected positions on the url ``@@overview-controlpanel`` . Here is the snippet of the same 
![error_theme](https://cloud.githubusercontent.com/assets/6854139/9658453/037eab46-5267-11e5-823c-4415e24ceb10.png)

**Comment by davilima6** [comment]
Made invalid by #78

**Comment by davilima6** [comment]
If you want to fix that for Plone 4.3, add `.visualClear { display: none; }` to `themes/example/assets/ploneui.css`
