### ISSUE TITLE
Positioning of multiple themes in theming control panel in Safari

### ISSUE THREAD

**Issue by MasterFox** [plone/plone.app.theming#79]
Safari interprets "display: inline-block" other than Firefox and Chrome. Therefore is a litte offset displaying multiple themes.

Display in Safari:
<img width="1078" alt="theming-control-panel-safari" src="https://cloud.githubusercontent.com/assets/8460465/9931561/f5ee96a4-5d3c-11e5-8450-1fc5f933cf7d.png">

Display in Firefox:
<img width="1089" alt="theming-control-panel-firefox" src="https://cloud.githubusercontent.com/assets/8460465/9931567/04e1b3bc-5d3d-11e5-8ae0-e3c2ee38c136.png">

**Comment by davilima6** [comment]
A float seems to fix it. Could someone please review and merge?
