### ISSUE TITLE
AttributeError: mark_special_links when saving theme details

### ISSUE THREAD

**Issue by pigeonflight** [plone/plone.app.theming#85]
Here's the traceback that shows up when attempting to save theme settings under:
Theming controlpanel > Advanced > Theme details

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.app.theming.browser.controlpanel, line 46, in __call__
  Module plone.app.theming.browser.controlpanel, line 200, in update
  Module plone.app.theming.browser.controlpanel, line 81, in set_mark_special_links
  Module plone.registry.recordsproxy, line 43, in __setattr__
AttributeError: mark_special_links

![plone app theming issues](https://cloud.githubusercontent.com/assets/31827/10062941/beb0b974-622d-11e5-9c96-50bafae69cef.gif)

**Comment by vangheem** [comment]
This a fresh site? I wonder if there is a missing upgrade step here.

**Comment by pigeonflight** [comment]
Just tested this on a fresh site just to be absolutely sure. Also completely wiped plone.app.theming and pulled the latest version from git using the coredev buildout.

I get the identical error, same traceback. 

see video: https://drive.google.com/a/alteroo.com/file/d/0B1mqNRWnzBQ2TnY5UkZfUnY5S1U/view

**Comment by pigeonflight** [comment]
Man... you beat me to the fix :)
I even made a pull request. Oh well....
